// Icon replacement for lucide-react using react-icons
import {
  FiCamera as Camera,
  FiStar as Sparkles,
  FiArrowRight as ArrowRight,
  FiArrowLeft as ArrowLeft,
  FiUsers as Users,
  FiHeart as Heart,
  FiDownload as Download,
  FiZap as Zap,
  FiShield as Shield,
  FiSmartphone as Smartphone,
  FiShare as Share,
  FiSave as Save,
  FiSettings as Settings,
  FiHome as Home,
  FiMail as Mail,
  FiLock as Lock,
  FiEye as Eye,
  FiEyeOff as EyeOff,
  FiUser as User,
  FiUpload as Upload,
  FiCheck as Check,
  FiX as X,
  FiMenu as Menu,
  FiLogOut as LogOut,
  FiTrash2 as Trash2,
  FiSearch as Search,
  FiFilter as Filter,
  FiGrid as Grid,
  FiList as List,
  FiShare2 as Share2,
  FiCalendar as Calendar,
  FiClock as Timer,
  FiMonitor as Monitor,
  FiChevronDown as ChevronDown,
  FiInfo as Info,
  FiCheckCircle as CheckCircle,
  FiXCircle as XCircle,
  FiAlertTriangle as AlertTriangle,
  FiAlertCircle as AlertCircle,
  FiLogIn as LogIn,
  FiMoon as Moon,
  FiSun as Sun,
  FiPlay as Play,
  FiPause as Pause,
  FiLayers as Layout,
  FiFolder as FolderOpen,
  FiImage as ImageIcon,
  FiPlus as Plus,
  FiRotateCcw as RotateCcwIcon,
  FiEdit2 as Edit2,
  FiEdit3 as Edit3,
  FiStar as Star,
  FiFolderPlus as FolderPlus,
  FiArrowDown as ArrowUpDown,
  FiLoader as Loader,
  FiFile as FileText,
  FiWifi as Wifi,
  FiWifiOff as WifiOff,
  FiCloud as Cloud,
  FiCloudOff as CloudOff
} from 'react-icons/fi'
import { MdPalette as Palette, MdGrid3X3 as Grid3X3 } from 'react-icons/md'

// Re-export all icons so they can be imported the same way as lucide-react
export {
  Camera,
  Sparkles,
  ArrowRight,
  ArrowLeft,
  Users,
  Heart,
  Download,
  Zap,
  Shield,
  Smartphone,
  Share,
  Save,
  Settings,
  Home,
  Mail,
  Lock,
  Eye,
  EyeOff,
  User,
  Upload,
  Check,
  X,
  Menu,
  LogOut,
  Trash2,
  Search,
  Filter,
  Grid,
  List,
  Share2,
  Calendar,
  Palette,
  Timer,
  Monitor,
  ChevronDown,
  Info,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  LogIn,
  Moon,
  Sun,
  Play,
  Pause,
  Grid3X3,
  Layout,
  FolderOpen,
  ImageIcon,
  Plus,
  Edit2,
  Edit3,
  Star,
  FolderPlus,
  ArrowUpDown,
  Loader,
  FileText,
  Wifi,
  WifiOff,
  Cloud,
  CloudOff
}

export const RotateCcw = RotateCcwIcon
export const TimerIcon = Timer
export const Image = ImageIcon
export const Folder = FolderOpen
